name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: "Checkout código"
        uses: actions/checkout@v4

      # --- ETAPA DE TESTE (CI) ---
      - name: "Configurar Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Instalar dependências"
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # - name: "Rodar Testes (Pytest)"
      #   env:
      #     SECRET_KEY: "test-key-ci"
      #     DEBUG: "True"
      #     DB_ENGINE: "django.db.backends.sqlite3"
      #     DB_NAME: ":memory:"
      #   run: pytest --cov=api

      # --- ETAPA DE DEPLOY (CD) ---
      - name: "Login na Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Login no Registro de Contêiner (ACR)"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: "Construir e Enviar Imagem Docker"
        run: |
          docker build -t ${{ secrets.ACR_NAME }}/easymiles-backend:latest -f Dockerfile .
          docker push ${{ secrets.ACR_NAME }}/easymiles-backend:latest

      - name: "Fazer deploy no App Service (Reiniciar)"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          images: "${{ secrets.ACR_NAME }}/easymiles-backend:latest"
